FROM rust:1.42-stretch as build
RUN rustup default nightly
RUN mkdir /build
COPY Cargo.toml /build
COPY src /build/src
RUN cd /build; cargo build

FROM debian:stable
RUN apt-get update
RUN apt-get install -y libssl1.1 ca-certificates
COPY --from=build /build/target/debug/mapexplorer /mapexplorer
COPY static /static
COPY templates /templates
COPY entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
